name: Build

on:
  push:
    branches: [ "feature/oss" ]
  pull_request:
    branches: [ "feature/oss" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11, windows-2019 ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: |
            20
            17
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        if: ${{ matrix.os != 'windows-2019' }}
        run: ./gradlew clean build --no-daemon -Dorg.gradle.java.installations.fromEnv=JAVA_HOME_20_X64
      - name: Build with Gradle on Windows
        if: ${{ matrix.os == 'windows-2019' }}
        run: ./gradlew clean build --no-daemon